name: SBOM/VEX generation

on:
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  sbom-vex-scan:
    name: SBOM/VEX Generation
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        project: [ "webgoat", "juice-shop" ]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Generate VEXs (Human)
        uses: aquasecurity/trivy-action@57a97c7e7821a5776cebc9bb87c984fa69cba8f1 # v0.35.0
        with:
          scan-type: fs
          scanners: vuln
          format: table
          output: ${{ matrix.project }}.vex
          scan-ref: ./vuln_apps/${{ matrix.project }}
        env:
          TRIVY_DB_REPOSITORY: "ghcr.io/aquasecurity/trivy-db,public.ecr.aws/aquasecurity/trivy-db"
          TRIVY_JAVA_DB_REPOSITORY: "ghcr.io/aquasecurity/trivy-java-db,public.ecr.aws/aquasecurity/trivy-java-db"

  

      - name: Upload results
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: vex-${{ matrix.project }}
          path: ${{ matrix.project }}.vex
          retention-days: 5
